# Generated by Django 5.1.6 on 2025-02-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'La critique', 'verbose_name_plural': 'Les critiques'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Le ticket', 'verbose_name_plural': 'Les tickets'},
        ),
        migrations.AlterField(
            model_name='review',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
