# Generated by Django 5.1.6 on 2025-02-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_review_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollows',
            options={'verbose_name': 'Utilisateur suivi', 'verbose_name_plural': 'Utilisateurs suivis'},
        ),
    ]
