# Generated by Django 5.1.6 on 2025-02-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': "Liste d'utilisateur", 'verbose_name_plural': 'Liste des utilisateurs'},
        ),
    ]
