# Generated by Django 5.1.6 on 2025-02-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_profile_photo_alter_user_role'),
    ]

    operations = [
    ]
